language: c++
dist: bionic

sudo: false

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - sudo apt-get install libjack-dev libsndfile1-dev libboost-program-options-dev

script:
  # Use CMake rather than plain makefile as it will allow to build .deb with CPack
  - mkdir build && cd build && cmake .. && make

notifications:
  email: false
